# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


plant_a = Plant.create(common_name: "Garden Tomato", latin_name: "Solanum Lycopersicum", description: "With hundreds of varieties to choose from, and more being introduced every year, there is a tomato for every garden situation and every personal taste. The size of the fruit is no indication of plant size -- tiny 'currant' tomatoes might grow on huge, vining (indeterminate) plants, while large 'beefsteak' varieties can be found on more manageable bush (determinate) plants. Newer hybrid varieties have been bred for disease resistance, but don't overlook heirlooms that are famous for their rich flavors. By planting early-, mid-, and late-season varieties, you can extend the harvest.", zone: "5-8", image: "https://i.pinimg.com/originals/5b/4c/71/5b4c7102f3e4cb915dfbef78aa4307b1.jpg
")
plant_b = Plant.create(common_name: "Dahlia", latin_name: "Dahlia Pinnata", description: "Dahlias are quick-growing, heat-loving plants that produce abundant flowers on sturdy stems. There are hundreds of varieties with flowers in a wide range of sizes, colors, and shapes.", zone: "2-11", image: "https://i.pinimg.com/originals/3f/ff/f5/3ffff5c8313031f14662d01bc9adebd0.jpg")
plant_c = Plant.create(common_name: "Lavender", latin_name: "Lavandula", description: "Lavender is the name given to several species of herbaceous, perennial shrubs in the genus Lavandula which are grown as ornamental plants or for essential oil. Lavender plants are small, branching and spreading shrubs with grey-green leaves and long flowering shoots. The leaves can be simple or pinnate measuring 30–50 mm (1–2 in) in length. The plant produces flowers on shoots or spikes which can be 20–40 cm (8–16 in) long. The flowers are lilac or blue in color. Lavender can grow to 0.4 m (1.3 ft) in height and live for 20–30 years. Lavender may also be referred to as true lavender, medical lavender, smelling lavender, thin-leaved lavender or English lavender and is believed to originate from the Mediterranean, Middle East and India.", zone: "5-9", image: "https://i.pinimg.com/originals/7e/a1/e8/7ea1e8e5b24b353ee1a5afd5fba56537.png
")
plant_d = Plant.create(common_name: "Pole Beans", latin_name: "Phaseolus Vulgaris", description: "Phaseolus vulgaris, also known as the common bean,[2] is a herbaceous annual plant grown worldwide for its edible dry seeds or unripe fruit (both commonly called beans). The main categories of common beans, on the basis of use, are dry beans (seeds harvested at complete maturity), snap beans (tender pods with reduced fibre harvested before the seed development phase) and shell (shelled) beans (seeds harvested at physiological maturity). Its leaf is also occasionally used as a vegetable and the straw as fodder. Its botanical classification, along with other Phaseolus species, is as a member of the legume family Fabaceae. Like most members of this family, common beans acquire the nitrogen they require through an association with rhizobia, which are nitrogen-fixing bacteria.", zone: "3-10", image: "https://i.pinimg.com/originals/dc/67/d1/dc67d193b614fc0a4f4a938b29b43f58.jpg
")
plant_e = Plant.create(common_name: "Dutchman's Pipe Vine", latin_name: "Aristolochia macrophylla" , description: "The plant is also called pipe vine and is suitable for gardens in USDA zones 8 to 10. The vine is usually only 10 to 15 feet (3 to 4.5 m.) long but can get as long as 25 feet (7.5 m.) in perfect growing conditions. Growing a Dutchman’s pipe requires a trellis or vertical structure to support the twining stems and wide foliage. The large heart-shaped leaves alternate along a woody stem. The flowers appear in late spring and early summer. They are a tinged plum color with speckles. An interesting bit of Dutchman’s pipe info is its one-time use as an aid to childbirth because of its resemblance to a human fetus. This property leads to another of the vine’s names, birthwort. Dutchman’s pipe vines are also host plants for swallowtail butterflies and provide habitat for beneficial insects.", zone: "8-10", image: "https://i.pinimg.com/originals/39/5f/d3/395fd32a4eed2515ba0b3540377e3639.jpg
")


p1 = Pollinator.create(name: "Pipevine Swallowtail", species: "Battus philenor", description: "This butterfly is black with iridescent-blue hindwings. They are found in many different habitats, but are most commonly found in forests.[3] Caterpillars are often black or red, and feed on compatible plants of the genus Aristolochia. They are known for sequestering acids from the plants they feed on in order to defend themselves from predators by being poisonous when consumed. The adults feed on the nectar of a variety of flowers. Some species of Aristolochia are toxic to the larvae, typically tropical varieties.", image:"https://c8.alamy.com/comp/P6H3T2/pipevine-swallowtail-butterfly-battus-philenor-14-and-black-swallowtwail-papilio-polyxenes-asterias-235-handcoloured-lithograph-from-john-o-westwoods-new-edition-of-dru-drurys-illustrations-of-exotic-entomology-bohn-london-1837-P6H3T2.jpg")

p2 = Pollinator.create(name: "Honey Bee", species: "Apis mellifera", description: "Honey bee is a widely distributed flying insect know for its ability to collect nectar from flowers and produce honey. Honey bees (right) are mustard yellow and brown. They have stocky bodies that are covered with many hairs to which pollen adheres.", image:"https://i.pinimg.com/originals/08/cb/f0/08cbf060c3d0f22d7c3f07207ea03c0a.png")

p3 = Pollinator.create(name: "Luna Moth", species: "Actias Luna", description: " It has lime-green colored wings and a white body. The larvae (caterpillars) are also green. Typically, it has a wingspan of roughly 114 mm (4.5 in), but can exceed 178 mm (7.0 in), making it one of the larger moths in North America. Across Canada, it has one generation per year, with the winged adults appearing in late May or early June, whereas farther south it will have two or even three generations per year, the first appearance as early as March in southern parts of the United States.", image: "https://i.pinimg.com/originals/0f/c8/f1/0fc8f1b47df448c2a013417320f3c108.jpg")

p4 = Pollinator.create(name: "Anna's Hummingbird", species: "Calypte Anna", description: "Anna’s Hummingbirds are among the most common hummingbirds along the Pacific Coast, yet they're anything but common in appearance. With their iridescent emerald feathers and sparkling rose-pink throats, they are more like flying jewelry than birds. Though no larger than a ping-pong ball and no heavier than a nickel, Anna’s Hummingbirds make a strong impression. In their thrilling courtship displays, males climb up to 130 feet into the air and then swoop to the ground with a curious burst of noise that they produce through their tail feathers.", image: "https://i.pinimg.com/originals/67/ba/ef/67baeff76122f70756df672851b04265.jpg")
p5 = Pollinator.create(name: "Common Wasp", species: "Vespula Vulgaris", description: "Vespula vulgaris is a eusocial vespid that builds its grey paper nest in or on a structure capable of supporting it. A founding queen searches for a hollow tree, wall cavity, rock crevice, or even a mammal-made hole to build a nest. One colony cycle lasts for about 6–11 months and each colony cycle consists of around 3000–8000 larvae.", image: "https://i.pinimg.com/originals/9c/e5/54/9ce554acb2ca0832ae5fa5618aa9d819.jpg")

pp1 = PlantPollinator.create(plant_id: plant_a.id, pollinator_id: p2.id)
pp2 = PlantPollinator.create(plant_id: plant_a.id, pollinator_id: p5.id)
pp3 = PlantPollinator.create(plant_id: plant_b.id, pollinator_id: p3.id)
pp4 = PlantPollinator.create(plant_id: plant_c.id, pollinator_id: p2.id)
pp5 = PlantPollinator.create(plant_id: plant_e.id, pollinator_id: p1.id)
pp6 = PlantPollinator.create(plant_id: plant_b.id, pollinator_id: p4.id)
